### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by xygkevin** [mihai8804858/swift-reachability#1]
Hi，do you know the enum of NWInterface.RadioType.Cellular? and how to use it?
<img width="831" alt="image" src="https://github.com/mihai8804858/swift-reachability/assets/19592642/4a416401-b38e-4ecd-9460-5894db5f4bd0">

**Comment by mihai8804858** [comment]
This seems to be part of [`NWConnection.DataTransferReport.PathReport
`](https://developer.apple.com/documentation/network/nwconnection/datatransferreport/pathreport) which is used for collecting network metrics. See [this](https://developer.apple.com/documentation/network/nwconnection/collecting_network_connection_metrics) example from Apple.
